title: "Pure Tones"
remote_theme: RMWinslow/just-the-docs-2
search_enabled: true

color_scheme: nil

gh_edit_link: false  # show or hide edit this page link

compress_html:
  ignore:
    envs: all

plugins:
  - jekyll-sitemap
  - jekyll-feed
