title: "Pure Tones"
remote_theme: RMWinslow/just-the-docs
search_enabled: true

color_scheme: solarized

gh_edit_link: false  # show or hide edit this page link

math_engine: nil

compress_html:
  ignore:
    envs: all

plugins:
  - jekyll-sitemap
  - jekyll-feed
