title: "Pure Tones"
remote_theme: RMWinslow/just-the-docs-tweaked
search_enabled: false

color_scheme: nil

gh_edit_link: false  # show or hide edit this page link

compress_html:
  ignore:
    envs: all

plugins:
  - jekyll-sitemap
  - jekyll-feed
